apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: start-pipeline
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/eduardoriveror/start
    targetRevision: HEAD
    path: tekton
  destination:
    server: https://kubernetes.default.svc
    namespace: tekton-pipelines