apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: start-deploy
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/eduardoriveror/start
    targetRevision: HEAD
    path: argocd-tst
  destination:
    server: https://kubernetes.default.svc
    namespace: start-dev
  syncPolicy:
    automated:
      prune: true